### ISSUE TITLE
Set up and running "call" 

### ISSUE THREAD

**Issue by aturnerhi** [CenikLab/satmut_utils#1] opened 2023-05-10 16:00 UTC
#### First time running satmututils "call" - I'm guessing this is a minor issue with my command line or a missing dependency, but I can't figure it out. The code throws the samtools error and then stops entirely. The whole code runs for less than 2 seconds, so I'm fairly sure it's a simple issue with my input formatting. 

$ conda activate satmut_utils
$satmut_utils -r WT_gcamp6s.fa -o /work/08274/aht669/SatTest/ call -1 ./NGS/Tile1_R1.fastq -2 ./NGS/Tile1_R2.fastq -v -m 1 -g TRPM8.gff -k GenomicMerge.fa 

#### In this case, WT_gcamp6s.fa is the fasta with my protein-coding plasmid, and GenomicMerge is the fasta containing the genomic DNA protein-coding sequence. I haven't yet included the primers, still working on making a BED file. 
[Files.zip](https://github.com/CenikLab/satmut_utils/files/11443938/Files.zip)

####Output is as follows
2023-05-10 10:29:20,825 - root - INFO - Started /work/08274/aht669/miniconda3/envs/satmut_utils/bin/satmut_utils
2023-05-10 10:29:20,826 - root - INFO - Starting call workflow.
2023-05-10 10:29:20,845 - root - INFO - Copying input reference FASTA and indexing.
2023-05-10 10:29:20,861 - analysis.references - INFO - Generating FASTA index file for /work/08274/aht669/SatTest/WT_rTRPM8_gcamp6s.fa.
2023-05-10 10:29:21,103 - analysis.references - INFO - Building FM index files for /work/08274/aht669/SatTest/WT_rTRPM8_gcamp6s.fa.
2023-05-10 10:29:21,474 - analysis.aligners - INFO - Started bowtie2 aligner workflow.
2023-05-10 10:29:21,475 - analysis.aligners - INFO - Writing output BAM /scratch/08274/aht669/tmp8wkouiqw.call.tmp/Tile1_S1_L001_R.bam
Traceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/satmut_utils", line 8, in <module>
    sys.exit(main())
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/satmut_utils/satmut_utils.py", line 526, in main
    keep_intermediates=args_dict["keep_intermediates"])
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/satmut_utils/satmut_utils.py", line 435, in call_workflow
    nthreads=bowtie2_nthreads)
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/scripts/run_bowtie2_aligner.py", line 82, in workflow
    bt = Bowtie2(config=bc, f1=f1, f2=f2, output_dir=outdir_full, output_bam=outbam)
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/analysis/aligners.py", line 117, in __init__
    self.workflow()
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/analysis/aligners.py", line 184, in workflow
    su.index_bam(self.output_bam)
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/analysis/seq_utils.py", line 328, in index_bam
    pysam.index(bam)
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/pysam/utils.py", line 89, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "/scratch/08274/aht669/tmp8wkouiqw.call.tmp/Tile1_S1_L001_R.bam" is in a format that cannot be usefully indexed\n'

**Comment by ijhoskins** [comment] 2023-05-10 17:08
Hi @aturnerhi, for custom references specify your plasmid FASTA for both -r and -k! I expect that will solve your issue. The configuration is strange but having both -r and -k was required to enable running satmut_utils with references downloaded from Ensembl.

**Comment by aturnerhi** [comment] 2023-05-10 17:20
Hi @ijhoskins, that's great info to know! I fixed that, but unfortunately, I'm still getting the same error message. I checked and it's an identical error message. At least we've fixed one potential problem! Is there anything else I should try?

**Comment by ijhoskins** [comment] 2023-05-10 17:50
@aturnerhi I see two issues in your example files.

The first is that the R1 and R2 do not appear to be paired properly, as the read names are not identical in R1 and R2.

Second is that the first field (seqid) and "transcript_id" attribute in your GFF file do not specify the same name as in your transcript FASTA. For each line in the GFF, the first field should be set to WT_rTRPM8_gcamp6s and the "transcript_id" should be present in each line and specify WT_rTRPM8_gcamp6s also.

Admittedly the configuration for the custom references is atypical, as normally standard GFF files specify the chromosome in the first field. For custom files, satmut_utils treats your plasmid FASTA as single transcript exon, with a single CDS feature defining the coordinates of the coding region.

The sample CBS_pEZY3.fa file is somewhat verbose with the attributes. The only attribute required on each line is "transcript_id"

**Comment by aturnerhi** [comment] 2023-05-10 18:57
Thanks for checking on that! I fixed the GFF file, thanks for the clarification! 
Maybe when I pulled the sample read names I missed a line and that's why the names aren't identical. The names are fine on the original files I got from the sequencing facility. Is it a requirement that the .fastq files be bzipped, zipped, or uncompressed? Would that make a difference? 
I've tried the pipeline again and I'm still getting the same error message.

**Comment by ijhoskins** [comment] 2023-05-10 19:02
Hi @aturnerhi satmut_utils works on either unzipped or gzipped FASTQ files. Can you share your new GFF? If you can also provide corrected sample FASTQs I can do some testing.

**Comment by ijhoskins** [comment] 2023-05-10 19:41
@aturnerhi it might be worth running the unit tests just to confirm things are working properly. To do this cd into the satmut_utils repository and execute 'nose2 -q'

**Comment by aturnerhi** [comment] 2023-05-10 19:51
Ok, ran unit tests: 

$ nose2 -q

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

**Comment by aturnerhi** [comment] 2023-05-10 19:52
[TRPM8.zip](https://github.com/CenikLab/satmut_utils/files/11445499/TRPM8.zip)

**Comment by ijhoskins** [comment] 2023-05-10 20:27
@aturnerhi did you see any message when executing the unit tests? I tested the CenikLab distribution and all unit tests are passing: 

Ran 171 tests in 42.992s
OK

Also, I attached corrected reference files. The exon record in the GFF should be the full length of the transcript and the stop_codon record should not overlap the CDS coordinates.

[TRPM8_fixed.zip](https://github.com/CenikLab/satmut_utils/files/11445730/TRPM8_fixed.zip)

**Comment by aturnerhi** [comment] 2023-05-10 20:44
Thank you so much for fixing that! GFF is a new file system for me. 
Ok, I ran the nose2 test again, this time with the verbose option. 
This time I got a very, very long error message. It says that it ran 175 tests and threw 10 error messages. There is probably something wrong with my installation, given the sheer number of errors it detected. The entire printout is below: 

......................................................[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R1.call.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R2.call.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R1.call.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R2.call.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmpuiim7xfn.R1.call.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmpuiim7xfn.R2.call.bam'
.........[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R1.call.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmppiu6zklb/tmp_9hqfyct.R2.call.bam'
...WARNING:analysis.read_editor:Sum of all variant frequencies exceeds (1 - the default max error rate of 0.030000). Some variants may not be edited due to preservation of errors.
Lines   total/split/realigned/skipped:  6/0/0/0
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/pybedtools.ireuutrw.tmp'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmp5z04dvkc.primer.intersected.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpkt37t030.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/pybedtools.2an7q6u9.tmp'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpqqrsubvk.primer.nonintersected.bam'
....WARNING:analysis.read_editor:Sum of all variant frequencies exceeds (1 - the default max error rate of 0.030000). Some variants may not be edited due to preservation of errors.
..............[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpgdzz5ec4.editor.preprocessor.tmp/tmpdw0a_2h2.qname.sort.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpdo82r012.temp.edit.bam'
.....[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpgdzz5ec4.editor.preprocessor.tmp/tmpdw0a_2h2.qname.sort.bam'
..................[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmp0fbhrpbz.bam'
...[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmp0fbhrpbz.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmp577mtozb.cdedup.bam'
.........[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpn_csw2co/tmpra9um2kw.consensus.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpn_csw2co/tmpnd36a3pg.consensus.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmptua_lu4r.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpg4uuniss.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmptmva9e4a.tag.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpd2pyyljh.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpspip0o8o.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpohuy035i.tag.bam'
.[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmp3yajhgg3.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpyit69pyp.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpcp4j4jjm.bam.preprocess.bam'
.Traceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
ETraceback (most recent call last):
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/bin/cutadapt", line 7, in <module>
    from cutadapt.cli import main_cli
  File "/work/08274/aht669/miniconda3/envs/satmut_utils/lib/python3.7/site-packages/cutadapt/cli.py", line 1065, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
E[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpijhtpg4y.bam'
.....[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpi43pm7af.bam'
..........[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpi43pm7af.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpescb2g52/tmpcym4r_ao.test.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/pybedtools.jkmsmrap.tmp'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpj948ime2.primer.intersected.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpbtncvs19.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpescb2g52/tmpcym4r_ao.test.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/pybedtools.rcyx7gtk.tmp'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpjtc6g_io.primer.nonintersected.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/08274/aht669/tmpescb2g52/tmpcym4r_ao.test.masked.bam'
................./work/08274/aht669/satmut_utils/src/analysis/coordinate_mapper.py:420: TranscriptomicCoordNotFound: Variant ENST00000398165.7:0:T:G position is not within transcript bounds.
  warnings.warn(msg_str, TranscriptomicCoordNotFound)
WARNING:analysis.coordinate_mapper:Variant ENST00000398165.7:0:T:G position is not within transcript bounds.
./work/08274/aht669/satmut_utils/src/analysis/coordinate_mapper.py:420: TranscriptomicCoordNotFound: Variant ENST00000398165.7:22756:T:G position is not within transcript bounds.
  warnings.warn(msg_str, TranscriptomicCoordNotFound)
WARNING:analysis.coordinate_mapper:Variant ENST00000398165.7:22756:T:G position is not within transcript bounds.
.ERROR:analysis.coordinate_mapper:REF T of ENST00000398165.7:260:T:G does not match the expected reference sequence of the transcript: C
NoneType: None
.....
======================================================================
ERROR: test_run_cutadapt_amp_r1_normal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of AMP R1 containing 5' and 3' adapters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 395, in test_run_cutadapt_amp_r1_normal_pair
    with open(fqp.trimmed_f1, "r") as r1_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmphzexamzn.amp.umi.R1.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_amp_r2_normal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of AMP R2 containing 3' adapter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 411, in test_run_cutadapt_amp_r2_normal_pair
    with open(fqp.trimmed_f2, "r") as r2_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmpm2ppz0ge.amp.umi.R2.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r1_abnormal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of Tile-seq R1 with target priming off the 5' adapter, leading to abnormal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 293, in test_run_cutadapt_tileseq_r1_abnormal_pair
    with open(fqp.trimmed_f1, "r") as r1_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp93s9gk1v.tileseq.R1.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r1_no_adapter (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests lack of adapter trimming of Tile-seq R1 without adapter readthrough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 258, in test_run_cutadapt_tileseq_r1_no_adapter
    with open(fqp.trimmed_f1, "r") as r1_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp93s9gk1v.tileseq.R1.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r1_normal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of Tile-seq R1 with adapter readthrough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 275, in test_run_cutadapt_tileseq_r1_normal_pair
    with open(fqp.trimmed_f1, "r") as r1_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp93s9gk1v.tileseq.R1.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r1_umi (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of Tile-seq UMI-containing R1 with adapter readthrough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 362, in test_run_cutadapt_tileseq_r1_umi
    with open(fqp.trimmed_f1, "r") as r1_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp8d0zetnb.tileseq.umi.R1.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r2_abnormal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of Tile-seq R2 with target priming off the R1 5' adapter, leading to abnormal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 345, in test_run_cutadapt_tileseq_r2_abnormal_pair
    with open(fqp.trimmed_f2, "r") as r2_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp5muvyg8d.tileseq.R2.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r2_no_adapter (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests lack of adapter trimming of Tile-seq R2 without adapter readthrough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 310, in test_run_cutadapt_tileseq_r2_no_adapter
    with open(fqp.trimmed_f2, "r") as r2_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp5muvyg8d.tileseq.R2.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r2_normal_pair (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests lack of adapter trimming of Tile-seq R1 without adapter readthrough.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 327, in test_run_cutadapt_tileseq_r2_normal_pair
    with open(fqp.trimmed_f2, "r") as r2_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmp5muvyg8d.tileseq.R2.trimmed.fq'

======================================================================
ERROR: test_run_cutadapt_tileseq_r2_umi (src.tests.analysis.test_read_preprocessor.TestFastqPreprocessor)
Tests adapter trimming of Tile-seq R2 with adapter readthrough paired with UMI-containing R1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/work/08274/aht669/satmut_utils/src/tests/analysis/test_read_preprocessor.py", line 379, in test_run_cutadapt_tileseq_r2_umi
    with open(fqp.trimmed_f2, "r") as r2_out_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/08274/aht669/tmpi3qo9190/tmpg77icmyn.tileseq.umi.R2.trimmed.fq'

----------------------------------------------------------------------
Ran 175 tests in 70.003s

FAILED (errors=10)

**Comment by ijhoskins** [comment] 2023-05-10 20:57
@aturnerhi the "[E::idx_find_and_load] Could not retrieve index file for X" message is really a warning from samtools (https://github.com/pysam-developers/pysam/issues/939) and can be ignored.

I'm not sure what may be the problem with the other tests. Can you let me know what version of satmut_utils you're running?

```
conda list | grep satmut-utils
```

**Comment by aturnerhi** [comment] 2023-05-10 21:14
Absolutely, version 1.0.2

Exact Output: 
satmut-utils              1.0.2                    pypi_0    pypi

**Comment by ijhoskins** [comment] 2023-05-10 21:17
What machine are you running on? Are you on TACC or a personal computer? I did a fresh install and tested the same version successfully on a Linux server.

**Comment by aturnerhi** [comment] 2023-05-10 21:19
I'm running on TACC. Bash shell, interactive job. Any chance any of these errors are related to insufficient memory/threads?

**Comment by ijhoskins** [comment] 2023-05-11 18:57
For posterity: I was able to reproduce the unit test errors on TACC. However, fresh installs pass tests on separate Linux and Mac OSX machines.

Test errors are caused by sys.stdout being None:
```
Traceback (most recent call last):
  File "/home1/06285/ihoskins/miniconda3/envs/satmut_utils_test/bin/cutadapt", line 7, in <module>
    from cutadapt.__main__ import main_cli
  File "/home1/06285/ihoskins/miniconda3/envs/satmut_utils_test/lib/python3.7/site-packages/cutadapt/__main__.py", line 881, in <module>
    def main(cmdlineargs, default_outfile=sys.stdout.buffer) -> Statistics:
AttributeError: 'NoneType' object has no attribute 'buffer'
```

**Comment by ijhoskins** [comment] 2023-06-26 21:58
@aturnerhi I should have been more clear about the cause of the failures.

satmut_utils is failing because cutadapt fails during import, which is in turn due to sys.stdout being None.

https://docs.python.org/3/library/sys.html#sys.__stdin__

However, as noted in the docs, sys.stdout being None is typically under the case where a script is run with pythonw, which is not the case for satmut_utils.

I believe another user ran into this problem as well (although I need to confirm). I still have yet to determine a good solution.

**Comment by ijhoskins** [comment] 2024-01-22 20:53
@aturnerhi are you still unable to run satmut_utils on TACC? I will close this issue for now, as I plan to containerize the software soon and this should get around platform-specific issues.

**Closed as completed by ijhoskins** 2024-01-22 20:53 UTC

**Comment by aturnerhi** [comment] 2024-01-22 21:00
Hi Ian,

I was able to run the updated version!

Thanks!
